### ISSUE TITLE
*** ImportError: cannot import name 'get_installed_distributions' from 'pip._internal.utils.misc' 

### ISSUE THREAD

**Issue by ealizadeh-via** [luffy-yu/conda_env_export#3]
I'm trying to import `from conda_env_export.conda_env_export import CondaEnvExport` but get the following error:

`*** ImportError: cannot import name 'get_installed_distributions' from 'pip._internal.utils.misc' `

This error occurs in an environment that I'm using pip version 22.2. I don't get this error in an environment with pip version 20.3.4. This suggest that latest pip major releases has a breaking changes for your library. 

There seems to be a solution for this and that involves using `pkg_resources` instead as can be seen in the following ticket: 
https://github.com/pypa/pip/issues/5243

I did a quick sanity check and I can confirm that the the results from `pkg_resources` is of a similar object return type from `get_installed_distributions` function as can be seen below:

![Screen Shot 2022-07-26 at 1 10 07 PM](https://user-images.githubusercontent.com/84460342/181071857-b71e0b0e-62ea-4590-accd-3e124bf57b89.png)

**Comment by luffy-yu** [comment]
You are right. I know this issue and that's the reason why I specify the pip version in its dependencies. 

Thanks for your hints. I will check that.

**Comment by luffy-yu** [comment]
Done. Please check the latest version `pip install conda-env-export==0.4.5`

**Comment by ealizadeh-via** [comment]
Thanks for your quick response and fix. I will check it tomorrow. This would automate another piece of my ML pipeline :)

**Comment by luffy-yu** [comment]
> Thanks for your quick response and fix. I will check it tomorrow. This would automate another piece of my ML pipeline :)

You are welcome. I really appreciate your feedback. And I'm glad to hear that it is useful for you.

**Comment by ealizadeh-via** [comment]
Your fix for both this issue and https://github.com/luffy-yu/conda_env_export/issues/4 works fine. Thanks
