### ISSUE TITLE
conda-env-export error: Failed to install conda, please install it manually

### ISSUE THREAD

**Issue by sgarcia-SBUHB** [luffy-yu/conda_env_export#7]
I have encountered an error while using `conda-env-export`. The package was successfully installed using `pip install conda-env-export` but failed when calling `conda-env-export`. Conda is added to the path but it seems that the package is not able to find in the second checking. 

`
    conda-env-export
    Checking conda......
    C:\Users\USERNAME\Anaconda3\condabin\..\Scripts\conda.exe
    Checking package menuinst......
    Found menuinst
    Checking package conda......   
    Not found conda, try to install automatically...
    Failed to install conda, please install it manually

`

**Comment by luffy-yu** [comment]
I am sorry for the late response. For some reason, I just see it.

Here we need pip package conda, not the conda executable file.

You can try install it via `pip install conda`.

**Comment by luffy-yu** [comment]
Fixed in [v0.5.0](https://github.com/luffy-yu/conda_env_export/tree/v0.5.0)
